# Default values for generic-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "hello-world-app"
fullnameOverride: "hello-world-app"

replicaCount: 1

container_properties:
  name: hello-world-app
  image:
    repository: appregistryterraform.azurecr.io/hello-world
    tag: 1
    pullPolicy: IfNotPresent  
  ports:
    name: port1
    containerPort: 8080
    protocol: TCP
  livenessProbe:
    path: /api/cms
    port: 8080
  readinessProbe:
    path: /api/cms
    port: 8080
  resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi    
  env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod      

service_properties:
  type: LoadBalancer
  ports:
    port: 80
    targetPort: 8080
    protocol: TCP
    name: port1

ingress_properties:
  enabled: false
  name: ingress-resource-badger-dev
  annotations: {}
    #kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls: {}
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
  # host: <hostURL>
  paths:
    - path: /api/cms
      backend:
        serviceName: hello-world-app
        servicePort: 8080

nodeSelector: {}

tolerations: []

affinity: {}
