variable "aks_name" {}
variable "aks_location" {}
variable "aks_resource_group_name" {}
variable "aks_dns_prefix" {}
variable "aks_default_node_pool_name" {}
variable "aks_default_node_pool_node_count" {}
variable "aks_default_node_pool_vm_size" {}
variable "client_id" {}
variable "client_secret" {}