apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-chart.fullname" . }}
  labels:
    app: {{ include "generic-chart.name" . }}
    chart: {{ include "generic-chart.chart" . }}
    #release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service_properties.type }}
  ports:
    - port: {{ .Values.service_properties.ports.port }}
      targetPort: {{ .Values.service_properties.ports.targetPort }}
      protocol: {{ .Values.service_properties.ports.protocol }}
      name: {{ .Values.service_properties.ports.name }}
  selector:
    app: {{ include "generic-chart.name" . }}
    #release: {{ .Release.Name }}
